apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-app1
  name: node-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app1
    spec:
      containers:
      - image: jashan98/nodeapp:9
        name: test
        resources: {}
status: {}
